databases:
  - name: defaultdb
    plan: free
    databaseName: defaultdb
    user: avnadmin

services:
  - type: web
    plan: free
    name: defaultdb
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python3 -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
        name: defaultdb
        property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings