# Generated by Django 3.2.12 on 2024-11-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.CharField(default='No description provided.', max_length=255)),
                ('github_url', models.URLField()),
            ],
        ),
    ]
