# Generated by Django 3.2.12 on 2024-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='No description provided.', max_length=255),
        ),
    ]
