# Generated by Django 3.2.12 on 2024-07-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_1', models.CharField(default=' ', max_length=1)),
                ('grid_2', models.CharField(default=' ', max_length=1)),
                ('grid_3', models.CharField(default=' ', max_length=1)),
                ('grid_4', models.CharField(default=' ', max_length=1)),
                ('grid_5', models.CharField(default=' ', max_length=1)),
                ('grid_6', models.CharField(default=' ', max_length=1)),
                ('grid_7', models.CharField(default=' ', max_length=1)),
                ('grid_8', models.CharField(default=' ', max_length=1)),
                ('grid_9', models.CharField(default=' ', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(default='X', max_length=1)),
                ('player_two', models.CharField(default='O', max_length=1)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.board')),
            ],
        ),
    ]
