# Generated by Django 3.2.12 on 2024-11-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='publication_date',
        ),
    ]
