# Generated by Django 6.0.4 on 2026-07-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_remove_post_body_remove_post_image_contentblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
